import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono, Poppins, Prata } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

//Criada a font Poppins da GOogle para usarsmos no projeto
const poppins = Poppins({
  variable: "--font-poppins", // Defina o nome da variável CSS
  subsets: ["latin"],         // Subconjuntos de caracteres
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  display: "swap", // (opcional) melhora o carregamento
});

// Fonte Prata (só tem uma variação de peso)
const prata = Prata({
  variable: "--font-prata",
  subsets: ["latin"],
  display: "swap",
  weight: "400"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// export const viewport: Viewport = {
//   width: "device-width",       // Largura baseada no dispositivo
//   initialScale: 1.0,           // Escala inicial
//   maximumScale: 1.0,           // Escala máxima (opcional)
//   userScalable: false,         // Se o usuário pode dar zoom (opcional)
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body
        className={`${poppins.variable} ${prata.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
